SP2-4029 first version - git message checker
ScholarPack/build-pipeline-tooling pull request #1
Opened 2021-04-12 07:51 UTC by CoburnJoe

First draft at the commit message checker script. Still to do:
- Update the regex to work with bitbucket merge commit messages
- Better docs - examples for use with both Bitbucket and GitHub builds

2021-04-12 13:49 UTC, nomad-software requested changes

2021-04-12 13:49 UTC, nomad-software commented on tools/commit-message-checker.sh
> +	if echo "$line" | grep -v -q -E "$PATTERN"; then
I'm not sure it matters but an uppercase `$PATTERN` is used here but all other usages are lowercase.

2021-04-12 13:49 UTC, nomad-software commented on tools/commit-message-checker.sh
> +echo "$COMMITS" | while read line ; do
Where does `$COMMITS` come from?

2021-04-12 13:49 UTC, nomad-software commented on tools/commit-message-checker.sh
> +		FAILURE=true
Just an idea, `FAILURE` could instead be `$EXIT_CODE`.

2021-04-12 14:00 UTC, CoburnJoe commented on tools/commit-message-checker.sh
> +echo "$COMMITS" | while read line ; do
Fixed 👍

2021-04-12 14:00 UTC, CoburnJoe commented on tools/commit-message-checker.sh
> +	if echo "$line" | grep -v -q -E "$PATTERN"; then
Fixed 👍

2021-04-12 14:02 UTC, CoburnJoe commented on tools/commit-message-checker.sh
> +		FAILURE=true
Changed to `requires_exit` 👍

2021-04-12 14:03 UTC, Marcus-UK approved these changes

2021-04-12 14:11 UTC, nomad-software approved these changes

2021-04-20 15:00 UTC, nomad-software approved these changes

2021-04-20 15:10 UTC, Marcus-UK approved these changes

2021-04-20 15:34 UTC, merged